spring :
#  jasypt:
#    encryptor:
#      password: ${SECRET_KEY}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-id}
            client-secret: ${google-secret}
            scope: profile,email
          naver:
            client-id: ${naver-id}
            client-secret: ${naver-secret}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

cloud:
  aws:
    region:
      static: ap-northeast-2  # AWS 기본 리전을 설정
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET}
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
